### ISSUE TITLE
Log message language consistency

### ISSUE THREAD

**Issue by tomas321** [brewmajsters/brewmaster-backend#2]
Please consider changing Slovak log messages to English on these lines:
- [x] https://github.com/brewmajsters/brewmaster-backend/blob/e18ac2b391d19ae1c5fdc203a50b2ff46acf5eb2/core/models/abstract/base_model.py#L26
- [x] https://github.com/brewmajsters/brewmaster-backend/blob/e18ac2b391d19ae1c5fdc203a50b2ff46acf5eb2/core/models/abstract/base_model.py#L39
- [x] https://github.com/brewmajsters/brewmaster-backend/blob/e18ac2b391d19ae1c5fdc203a50b2ff46acf5eb2/core/models/abstract/base_model.py#L50

**Comment by zurek11** [comment]
This issue will be fixed in the next release. Thank you.
