### ISSUE TITLE
.env.example should be not require renaming 

### ISSUE THREAD

**Issue by tomas321** [brewmajsters/brewmaster-backend#3]
Consider renaming the `.env.exmaple` file to `.env` as you request in the installation and setup process. Does leaving it as .env.example have inner meaning? Looking at its usage I suppose this setup step is redundant and can be removed.

**Comment by zurek11** [comment]
.env file is used to configure the project for the device on which it will be deployed. To implement the solution on multiple devices and to avoid overwriting the file, the .env file is in the .gitignore and .env.example file as an example, which is renamed to .env after deployment and changes to values according to deployment requirements.

**Comment by tomas321** [comment]
Thank you for the clarification
