### ISSUE TITLE
Absolute path for .env file

### ISSUE THREAD

**Issue by tomas321** [brewmajsters/brewmaster-backend#6]
https://github.com/brewmajsters/brewmaster-backend/blob/bee05aa969a3deb1874deecfcd814ba3542ec4d8/settings/base.py#L10

Please consider changing the path to `.env` file from relative to absolute. perhaps by utilizing this:

https://github.com/brewmajsters/brewmaster-backend/blob/bee05aa969a3deb1874deecfcd814ba3542ec4d8/settings/base.py#L20

**Comment by zurek11** [comment]
Merged.
